# Generated by Django 3.2.6 on 2021-11-14 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_sentry_dsn'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=64)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('primary_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_issues', to='events.event')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.issue'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project_id'], name='ix__issue__project_id'),
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('project_id', 'signature')},
        ),
    ]
