# Generated by Django 5.1.6 on 2025-02-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_remove_issue_primary_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
