# Generated by Django 3.2.12 on 2022-10-16 11:57

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_auto_20211114_2050"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "message",
                    "log_message",
                    "exception_message",
                    config="english",
                ),
                name="events_search_vector_idx",
            ),
        ),
    ]
