# Generated by Django 5.1.6 on 2025-02-15 10:56

from django.db import migrations


def set_issue_title(apps, schema_editor):
    Issue = apps.get_model("events", "Issue")
    Event = apps.get_model("events", "Event")
    for issue in Issue.objects.all():
        event = Event.objects.filter(issue=issue).first()
        if event:
            issue.title = event.message
        else:
            issue.title = f"Issue {issue.id}"
        issue.save()


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_issue_title"),
    ]

    operations = [
        migrations.RunPython(set_issue_title),
    ]
