# Generated by Django 5.1.6 on 2025-02-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_auto_20250215_1056"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="title",
            field=models.TextField(),
        ),
    ]
