# Generated by Django 3.2.6 on 2021-09-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sentry_dsn',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
