# Generated by Django 3.2.6 on 2021-11-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_sentry_dsn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sentry_dsn',
        ),
    ]
