[tool.black]
line-length = 79
target-version = ['py39']
extend-exclude = '''
(
  ^/manage.py
  | ^/vedette/settings.py
  | ^/events/migrations/.*$
  | ^/projects/migrations/.*$
  | ^/web/migrations/.*$
  | ^/api/migrations/.*$
)
'''
